### ISSUE TITLE
Request for link prediction datasets in MATLAB format

### ISSUE THREAD

**Issue by Newiz430** [qiaoyu-tan/S2GAE#4]
@qiaoyu-tan I’m trying to run this code as a baseline of our work. Nevertheless, the link prediction task needs the social network datasets in MATLAB format and they’re not provided apart from Cora. I somehow managed to find Citeseer.mat and Pubmed.mat but failed to find the rest of them (Photo, Comp, CS, Physics). Could you please provide them or a link to download them for free? Your help will be much appreciated!

**Comment by Newiz430** [comment]
Thanks for the kindly email reply! I'm truly grateful :)

**Comment by LeslieWu999** [comment]
I have the same question, is it possible to share the Flickr and BlogCatalog dataset in the .mat format with me? Thanks a lot!
